Templates = {};

Templates.Single = [
  '<div class="q" id="q{{id}}" hidden>',
    '<div class="questionContainer">',
			'<h3>Chapter {{reference}}</h3>',
			'<h4>Difficulty: {{difficulty}}</h4>',
			'<div>{{{question}}}</div>',
			'{{#images}}',
			'<div class="captionedimage">',
				'<img src="{{url}}"></img>',
				'<div>{{{caption}}}</div>',
			'</div>',
			'{{/images}}',
			'{{#graphs}}',
			'<svg id="{{graph}}"></svg>',
			'{{/graphs}}',
		'</div>',
		'<div class="answerContainer">',
			'<table class="selection">',
				'{{#answers}}',
				'<tr><td>{{{answer}}}</td><td><input type="radio" id="{{index}}_{{id}}" name="{{id}}"></input></td></tr>',
				'{{/answers}}',
			'</table>',
		'</div>',
		'<script>',
			'function submit_{{id}}() {',
				'if(document.getElementById("{{correct}}_{{id}}").checked)',
					'submit(true, {{id}});',
				'else',
					'submit(false, {{id}});',
			'}',
		'</script>',
		'<div id="submit"><button id="submit" onclick="submit_{{id}}()">Submit!</button></div>',
		'<div class="hint">',
			'<a onclick="$(\'#hint_{{id}}\').toggle()">Show Hint</a>',
			'<p id="hint_{{id}}" style="display: none;">{{{hint}}}</p>',
		'</div>',
	'</div>'
].join('\n');

Templates.Multiple = [
	'<div class="q" id="q{{id}}" hidden>',
		'<div class="questionContainer">',
			'<h3>Chapter {{reference}}</h3>',
			'<h4>Difficulty: {{difficulty}}</h4>',
			'<div>{{{question}}}</div>',
			'{{#images}}',
			'<div class="captionedimage">',
				'<img src="{{url}}"></img>',
				'<div>{{{caption}}}</div>',
			'</div>',
			'{{/images}}',
		'</div>',
		'<div class="answerContainer">',
			'<table class="selection">',
				'{{#answers}}',
				'<tr><td>{{{answer}}}</td><td><input type="checkbox" id="{{index}}_{{id}}"></input></td></tr>',
				'{{/answers}}',
			'</table>',
		'</div>',
		'<script>',
			'function submit_{{id}}() {',
				'var result = true;',
				'var answers = [{{#answers}}"{{correctness}}", {{/answers}}];',
				'for(var i in answers)',
					'if(answers[i] == "-" && document.getElementById(i + "_{{id}}").checked || ',
					'answers[i] == "+" && !document.getElementById(i + "_{{id}}").checked)',
						'result = false;',
				'submit(result, {{id}});',
			'}',
		'</script>',
		'<div id="submit"><button id="submit" onclick="submit_{{id}}()">Submit!</button></div>',
		'<div class="hint">',
			'<a onclick="$(\'#hint_{{id}}\').toggle()">Show Hint</a>',
			'<p id="hint_{{id}}" style="display: none;">{{{hint}}}</p>',
		'</div>',
	'</div>'
].join('\n');

Templates.Sort = [
	'<div class="q" id="q{{id}}" hidden>',
		'<div class="questionContainer">',
			'<h3>Chapter {{reference}}</h3>',
			'<h4>Difficulty: {{difficulty}}</h4>',
			'<div>{{{question}}}</div>',
			'{{#images}}',
			'<div class="captionedimage">',
				'<img src="{{url}}"></img>',
				'<div>{{{caption}}}</div>',
			'</div>',
			'{{/images}}',
		'</div>',
		'<div class="answerContainer">',
			'<div class="sortList">',
				'{{#answers}}',
				'<div id="{{index}}_{{id}}" class="sortItem" draggable="true" ondragstart="drag(event)" ',
				'ondragenter="sortDragover(event, {{id}})" ondragend="drop(event)"><span>⠿</span>{{{answer}}}<span>⠿</span></div>',
				'{{/answers}}',
			'</div>',
		'</div>',
		'<script>',
			'order_{{id}} = [{{#answers}}"{{index}}_{{id}}", {{/answers}}];',
			'function submit_{{id}}() {',
				'answers = [{{#answers}}{{correctness}}, {{/answers}}]',
				'var result = true;',
				'for(var i in answers) {',
					'if(answers[i] != order_{{id}}.indexOf(i + "_{{id}}") + 1)',
						'result = false;',
				'}',
				'submit(result, {{id}});',
			'}',
		'</script>',
		'<div id="submit"><button id="submit" onclick="submit_{{id}}()">Submit!</button></div>',
		'<div class="hint">',
			'<a onclick="$(\'#hint_{{id}}\').toggle()">Show Hint</a>',
			'<p id="hint_{{id}}" style="display: none;">{{{hint}}}</p>',
		'</div>',
	'</div>'
].join('\n');

Templates.Blank = [
	'<div class="q" id="q{{id}}" hidden>',
		'<div class="questionContainer">',
			'<h3>Chapter {{reference}}</h3>',
			'<h4>Difficulty: {{difficulty}}</h4>',
			'{{#images}}',
			'<div class="captionedimage">',
				'<img src="{{url}}"></img>',
				'<div>{{{caption}}}</div>',
			'</div>',
			'{{/images}}',
			'<div><i>Fill in the blanks</i></div>',
		'</div>',
		'<div class="answerContainer">',
			'<div>{{{question}}}</div>',
		'</div>',
		'<script>',
			'function submit_{{id}}() {',
				'var answers = [{{#answers}}[{{{answer}}}] ,{{/answers}}]',
				'var result = true;',
				'for(var i in answers)',
					'result = answers[i].indexOf($("#" + i + "_{{id}}").val().toLowerCase()) >= 0 && result;',
				'submit(result, {{id}});',
			'}',
		'</script>',
		'<div id="submit"><button id="submit" onclick="submit_{{id}}()">Submit!</button></div>',
		'<div class="hint">',
			'<a onclick="$(\'#hint_{{id}}\').toggle()">Show Hint</a>',
			'<p id="hint_{{id}}" style="display: none;">{{{hint}}}</p>',
		'</div>',
	'</div>'
].join('\n');

Templates.Cloze = [
	'<div class="q" id="q{{id}}" hidden>',
		'<div class="questionContainer">',
			'<h3>Chapter {{reference}}</h3>',
			'<h4>Difficulty: {{difficulty}}</h4>',
			'<div>{{{question}}}</div>',
			'{{#images}}',
			'<div class="captionedimage">',
				'<img src="{{url}}"></img>',
				'<div>{{{caption}}}</div>',
			'</div>',
			'{{/images}}',
		'</div>',
		'<div class="answerContainer">',
			'<table class="cloze" cellspacing="0">',
				'<tr>',
					'<th width="120"></th>',
					'<th><b>Predicted +</b></th>',
					'<th><b>Predicted -</b></th>',
					'<th></th>',
				'</tr>',
				'<tr>',
					'<td><b>Actual +</b></td>',
					'<td><input id="0_{{id}}"></input></td>',
					'<td><input id="1_{{id}}"></input></td>',
					'<td><input id="2_{{id}}"></input></td>',
				'</tr>',
				'<tr>',
					'<td><b>Actual -</b></td>',
					'<td><input id="3_{{id}}"></input></td>',
					'<td><input id="4_{{id}}"></input></td>',
					'<td><input id="5_{{id}}"></input></td>',
				'</tr>',
				'<tr>',
					'<td></td>',
					'<td><input id="6_{{id}}"></input></td>',
					'<td><input id="7_{{id}}"></input></td>',
					'<td><input id="8_{{id}}"></input></td>',
				'</tr>',
			'</table>',
		'</div>',
		'<script>',
			'function submit_{{id}}() {',
				'var answers = [{{{answers}}}]',
				'var result = true;',
				'for(var i in answers)',
					'if(answers[i] != $("#" + i + "_{{id}}").val()) result = false;',
				'submit(result, {{id}});',
			'}',
		'</script>',
		'<div id="submit"><button id="submit" onclick="submit_{{id}}()">Submit!</button></div>',
		'<div class="hint">',
			'<a onclick="$(\'#hint_{{id}}\').toggle()">Show Hint</a>',
			'<p id="hint_{{id}}" style="display: none;">{{{hint}}}</p>',
		'</div>',
	'</div>'
].join('\n');

Templates.Matrix = [
	'<div class="q" id="q{{id}}" hidden>',
		'<div class="questionContainer">',
			'<h3>Chapter {{reference}}</h3>',
			'<h4>Difficulty: {{difficulty}}</h4>',
			'<div>{{{question}}}</div>',
			'{{#images}}',
			'<div class="captionedimage">',
				'<img src="{{url}}"></img>',
				'<div>{{{caption}}}</div>',
			'</div>',
			'{{/images}}',
		'</div>',
		'<div class="answerContainer">',
			'<div class="matrixMultipleDrop" id="multipleDrop_{{id}}" ondrop="matrixDrop(event, {{id}})" ondragover="event.preventDefault()" ondragenter="matrixDragover(event)" ondragleave="matrixDragleave(event)">',
				'{{#answers}}',
				'<div id="{{position}}_{{id}}" class="matrixItem" draggable="true" ondragend="drop(event)" ondragstart="drag(event)">{{{answer}}}</div>',
				'{{/answers}}',
			'</div>',
			'<table class="matrixList">',
				'{{#questions}}',
				'<tr>',
					'<td>{{{question}}}</td>',
					'<td>',
						'<div class="matrixSingleDrop" id="{{index}}_{{id}}_drop" ondrop="matrixDrop(event, {{id}})" ondragover="event.preventDefault()" ondragenter="matrixDragover(event)" ondragleave="matrixDragleave(event)">',
						'</div>',
					'</td>',
				'</tr>',
				'{{/questions}}',
			'</table>',
		'</div>',
		'<script>',
			'var order_{{id}} = [{{#answers}}-1,{{/answers}}];',
			'function submit_{{id}}() {',
				'answers = [{{#answers}}{{index}},{{/answers}}]',
				'var result = true;',
				'for(var i in answers)',
					'result = (answers[i] + "_{{id}}_drop" == order_{{id}}[i]) && result;',
				'submit(result, {{id}});',
			'}',
		'</script>',
		'<div id="submit"><button id="submit" onclick="submit_{{id}}()">Submit!</button></div>',
		'<div class="hint">',
			'<a onclick="$(\'#hint_{{id}}\').toggle()">Show Hint</a>',
			'<p id="hint_{{id}}" style="display: none;">{{{hint}}}</p>',
		'</div>',
	'</div>'
].join('\n');

Templates.Default = [
	'<div id="q{{id}}" hidden>',
		'<div>ERROR: QUESTION TYPE DOES NOT EXIST</div>',
	'</div>'
].join('\n');

Templates.Score = [
	'<div id="q{{id}}" class="score" hidden>',
		'<h1>Final Score:</h1>',
		'<h1><span id="score">0</span>/<span id="score_total">0</span></h1><br>',
		'{{#workings}}',
		'<div id="{{id}}_score">',
			'<div>',
				'<div><a onclick="onclick=\'setQuestion({{id}})\'"><b>Goto Question {{id}}</b></a></div>',
				'<div class="workings">',
					'<div><a onclick="$(\'#{{id}}_working\').toggle()"><u>Show/Hide Workings</u></a></div>',
					'<div id="{{id}}_working" style="display: none;">{{{working}}}</div>',
				'</div>',
			'</div>',
		'</div>',
		'<br>',
		'{{/workings}}',
	'</div>'
].join('\n');

Templates.Scripts = [
	'<script>',

	'var question = 0;',

	'$("#left").attr("disabled", true);',
	'if($(".q").length <= 0) $("#right").attr("disabled", true);',
	'$("#q0").attr("hidden", false);',

	'function setQuestion(id) {',
		'$("#q" + question.toString()).attr("hidden", true);',
		'question = id;',
		'$("#right").attr("disabled", false);',
		'$("#left").attr("disabled", false);',
		'if(question == 0) $("#left").attr("disabled", true);',
		'if(question == $(".q").length) $("#right").attr("disabled", true);',
		'$("#q" + question.toString()).attr("hidden", false);',
	'}',

	'function prevQuestion() {',
		'$("#q" + question.toString()).attr("hidden", true);',
		'question -= 1;',
		'if(question == 0) $("#left").attr("disabled", true);',
		'$("#right").attr("disabled", false);',
		'$("#q" + question.toString()).attr("hidden", false);',
	'};',

	'function nextQuestion() {',
		'$("#q" + question.toString()).attr("hidden", true);',
		'question += 1;',
		'if(question == $(".q").length) $("#right").attr("disabled", true);',
		'$("#left").attr("disabled", false);',
		'$("#q" + question.toString()).attr("hidden", false);',
		'$(".correctnessOverlay").attr("hidden", true);',
		'if(question == $(".q").length) {',
			'$("#score").html(correct.reduce(function add(a, b) {return a + b;}, 0));',
			'$("#score_total").html($(".q").length)',
			'for(var i in correct){',
				'if(correct[i] == 1) { $("#" + i + "_score").css("background-color", "#88ff88"); $("#" + i + "_scorevalue").html("✓"); }',
				'else { $("#" + i + "_score").css("background-color", "#ff8888"); $("#" + i + "_scorevalue").html("✖"); }',
			'}',
		'}',
	'};',

	'var correct = [];',
	'for(var i = 0; i < $(".q").length; i++) correct.push(0);',

	'function submit(correctness, id) {',
		'if (correctness) {',
			'$("#correctOverlay").attr("hidden", false);',
			'correct[id] = 1;',
		'} else if (!correctness) {',
			'$("#correctnesshint").html( "<b>" + $("#hint_" + id).html() + "</b>" )',
			'$("#incorrectOverlay").attr("hidden", false);',
			'correct[id] = 0;',
		'}',
	'}',

	'dragging = 0;',

	'function drag(e) {',
		'var target = $(e.target);',
		'dragging = target.attr("id");',
		'setTimeout(function() {',
			'$("#" + dragging).addClass("dragHidden");',
		'}, 1);',
	'};',

	'function sortDragover(e, id) {',
		'e.preventDefault();',
		'var order = eval("order_" + id)',
		'if(order.indexOf(e.target.id) > order.indexOf(dragging)) {',
			'order.splice(order.indexOf(dragging), 1);',
			'order.splice(order.indexOf(e.target.id) + 1, 0, dragging);',
			'$("#" + dragging).insertAfter("#" + e.target.id);',
		'} else if(order.indexOf(e.target.id) < order.indexOf(dragging)) {',
			'order.splice(order.indexOf(e.target.id), 1);',
			'order.splice(order.indexOf(dragging) + 1, 0, e.target.id);',
			'$("#" + dragging).insertBefore("#" + e.target.id);',
		'}',
	'};',

	'function matrixDragover(e) {',
		'e.preventDefault();',
		'var target = $(e.target);',
		'while(target.attr("class") != "matrixSingleDrop" && target.attr("class") != "matrixMultipleDrop" && target.attr("class") != "answerContainer")',
			'target = target.parent();',
		'if(target.attr("class") == "matrixMultipleDrop")',
			'target.css("background-color", "rgba(0,0,0,0.2)");',
		'if(target.attr("class") == "matrixSingleDrop")',
			'target.css("border", "solid 2px #444");',
	'};',

	'function matrixDragleave(e) {',
	'e.preventDefault();',
	'var target = $(e.target);',
	'while(target.attr("class") != "matrixSingleDrop" && target.attr("class") != "matrixMultipleDrop" && target.attr("class") != "answerContainer")',
		'target = target.parent();',
		'if(target.attr("class") == "matrixMultipleDrop")',
			'target.css("background-color", "");',
		'if(target.attr("class") == "matrixSingleDrop")',
			'target.css("border", "");',
	'};',

	'function matrixDrop(e, id) {',
		'e.preventDefault();',
		'var order = eval("order_" + id)',
		'var n = parseInt(dragging.replace(/_[\\d]*/g, ""));',
		'var target = $(e.target);',
		'while(target.attr("class") != "matrixSingleDrop" && target.attr("class") != "matrixMultipleDrop" && target.attr("class") != "answerContainer")',
			'target = target.parent();',
		'if(target.attr("class") == "matrixMultipleDrop")',
		'{',
			'order[n] = -1;',
			'target.append($("#" + dragging));',
			'target.css("background-color", "");',
		'}',
		'if(target.attr("class") == "matrixSingleDrop")',
		'{',
			'if (target.children().length > 0)',
			'{',
				'var d = parseInt(target.children().attr("id").replace(/_[\\d]*/g, ""));',
				'order[d] = -1;',
				'$("#multipleDrop_" + id).append(target.children());',
			'}',
			'order[n] = target.attr("id");',
			'target.append($("#" + dragging));',
			'target.css("border", "");',
		'}',
	'};',

	'function drop(e) {',
		'$("#" + dragging).removeClass("dragHidden"),',
		'dragging = 0;',
	'};',

	'</script>'
].join('\n');

Templates.Header = [
	'<div class="header">',
		'<button id="left" onclick="prevQuestion()"><</button>',
		'<h1>{{title}}</h1>',
		'<button id="right" onclick="nextQuestion()">></button>',
	'</div>',

	'<div class="correctnessOverlay" id="correctOverlay" hidden>',
		'<div class="correctness">',
			'<svg mlns="http://www.w3.org/2000/svg" viewbox="0, 0, 150, 100" class="correctnessSVG">',
				'<path class="appear tick" d="M 112 25 L 57 70 L 37 43" stroke="white" stroke-dasharray="200,200" stroke-width="12" fill="none"/>',
			'</svg>',
			'<button id="correctnessButton" onclick="nextQuestion()">Next</button>',
		'</div>',
	'</div>',

	'<div class="correctnessOverlay" id="incorrectOverlay" hidden>',
		'<div class="correctness">',
			'<svg mlns="http://www.w3.org/2000/svg" viewbox="0, 0, 150, 100" class="correctnessSVG">',
				'<path class="appear cross" d="M 100 25 L 50 75" stroke="white" stroke-dasharray="200,200" stroke-width="12" fill="none"/>',
				'<path class="appear cross" d="M 50 25 L 100 75" stroke="white" stroke-dasharray="200,200" stroke-width="12" fill="none"/>',
			'</svg>',
			'<button id="correctnessButton" onclick="$(\'.correctnessOverlay\').attr(\'hidden\', true)">Retry</button>',
		'</div>',
		'<p id="correctnesshint"></p>',
	'</div>'
].join('\n');
